package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mstaffiliation generated by hbm2java
 */
@Entity
@Table(name = "mstaffiliation", catalog = "dbschoolmanagementsystem")
public class Mstaffiliation implements java.io.Serializable {

	private Integer intAffiliationId;
	private String txtAffiliation;
	private Set<Mstregistration> mstregistrations = new HashSet<Mstregistration>(0);

	public Mstaffiliation() {
	}

	public Mstaffiliation(String txtAffiliation, Set<Mstregistration> mstregistrations) {
		this.txtAffiliation = txtAffiliation;
		this.mstregistrations = mstregistrations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intAffiliationId", unique = true, nullable = false)
	public Integer getIntAffiliationId() {
		return this.intAffiliationId;
	}

	public void setIntAffiliationId(Integer intAffiliationId) {
		this.intAffiliationId = intAffiliationId;
	}

	@Column(name = "txtAffiliation", length = 50)
	public String getTxtAffiliation() {
		return this.txtAffiliation;
	}

	public void setTxtAffiliation(String txtAffiliation) {
		this.txtAffiliation = txtAffiliation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mstaffiliation")
	public Set<Mstregistration> getMstregistrations() {
		return this.mstregistrations;
	}

	public void setMstregistrations(Set<Mstregistration> mstregistrations) {
		this.mstregistrations = mstregistrations;
	}

}
