package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mstbank generated by hbm2java
 */
@Entity
@Table(name = "mstbank", catalog = "dbschoolmanagementsystem")
public class Mstbank implements java.io.Serializable {

	private Integer intBankId;
	private Mstfy mstfy;
	private Mstregistration mstregistration;
	private Tblbankname tblbankname;
	private String txtBankAccountNo;
	private String txtCtc;
	private String txtIfsccode;

	public Mstbank() {
	}

	public Mstbank(Mstfy mstfy, Mstregistration mstregistration, Tblbankname tblbankname, String txtBankAccountNo,
			String txtCtc, String txtIfsccode) {
		this.mstfy = mstfy;
		this.mstregistration = mstregistration;
		this.tblbankname = tblbankname;
		this.txtBankAccountNo = txtBankAccountNo;
		this.txtCtc = txtCtc;
		this.txtIfsccode = txtIfsccode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intBankId", unique = true, nullable = false)
	public Integer getIntBankId() {
		return this.intBankId;
	}

	public void setIntBankId(Integer intBankId) {
		this.intBankId = intBankId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intFYId")
	public Mstfy getMstfy() {
		return this.mstfy;
	}

	public void setMstfy(Mstfy mstfy) {
		this.mstfy = mstfy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intRegistrationId")
	public Mstregistration getMstregistration() {
		return this.mstregistration;
	}

	public void setMstregistration(Mstregistration mstregistration) {
		this.mstregistration = mstregistration;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intBankNameId")
	public Tblbankname getTxtBankName() {
		return this.tblbankname;
	}

	public void setTxtBankName(Tblbankname tblbankname) {
		this.tblbankname = tblbankname;
	}

	@Column(name = "txtBankAccountNo", length = 50)
	public String getTxtBankAccountNo() {
		return this.txtBankAccountNo;
	}

	public void setTxtBankAccountNo(String txtBankAccountNo) {
		this.txtBankAccountNo = txtBankAccountNo;
	}

	@Column(name = "txtCTC", length = 50)
	public String getTxtCtc() {
		return this.txtCtc;
	}

	public void setTxtCtc(String txtCtc) {
		this.txtCtc = txtCtc;
	}

	@Column(name = "txtIFSCCode", length = 20)
	public String getTxtIfsccode() {
		return this.txtIfsccode;
	}

	public void setTxtIfsccode(String txtIfsccode) {
		this.txtIfsccode = txtIfsccode;
	}

}
