package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mstdocumentsupload generated by hbm2java
 */
@Entity
@Table(name = "mstdocumentsupload", catalog = "dbschoolmanagementsystem")
public class Mstdocumentsupload implements java.io.Serializable {

	private Integer intDocumentsUploadId;
	private Mstsubcategory mstsubcategory;
	private Trndocumentupload trndocumentupload;
	private String txtDesc;

	public Mstdocumentsupload() {
	}

	public Mstdocumentsupload(Mstsubcategory mstsubcategory, Trndocumentupload trndocumentupload, String txtDesc) {
		this.mstsubcategory = mstsubcategory;
		this.trndocumentupload = trndocumentupload;
		this.txtDesc = txtDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intDocumentsUploadId", unique = true, nullable = false)
	public Integer getIntDocumentsUploadId() {
		return this.intDocumentsUploadId;
	}

	public void setIntDocumentsUploadId(Integer intDocumentsUploadId) {
		this.intDocumentsUploadId = intDocumentsUploadId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intSubCategoryId")
	public Mstsubcategory getMstsubcategory() {
		return this.mstsubcategory;
	}

	public void setMstsubcategory(Mstsubcategory mstsubcategory) {
		this.mstsubcategory = mstsubcategory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intDocumentUploadId")
	public Trndocumentupload getTrndocumentupload() {
		return this.trndocumentupload;
	}

	public void setTrndocumentupload(Trndocumentupload trndocumentupload) {
		this.trndocumentupload = trndocumentupload;
	}

	@Column(name = "txtDesc", length = 50)
	public String getTxtDesc() {
		return this.txtDesc;
	}

	public void setTxtDesc(String txtDesc) {
		this.txtDesc = txtDesc;
	}

}
