package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mstfy generated by hbm2java
 */
@Entity
@Table(name = "mstfy", catalog = "dbschoolmanagementsystem")
public class Mstfy implements java.io.Serializable {

	private Integer intFyid;
	private String txtFyname;
	private Set<Mstbank> mstbanks = new HashSet<Mstbank>(0);

	public Mstfy() {
	}

	public Mstfy(String txtFyname, Set<Mstbank> mstbanks) {
		this.txtFyname = txtFyname;
		this.mstbanks = mstbanks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intFYId", unique = true, nullable = false)
	public Integer getIntFyid() {
		return this.intFyid;
	}

	public void setIntFyid(Integer intFyid) {
		this.intFyid = intFyid;
	}

	@Column(name = "txtFYName", length = 50)
	public String getTxtFyname() {
		return this.txtFyname;
	}

	public void setTxtFyname(String txtFyname) {
		this.txtFyname = txtFyname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mstfy")
	public Set<Mstbank> getMstbanks() {
		return this.mstbanks;
	}

	public void setMstbanks(Set<Mstbank> mstbanks) {
		this.mstbanks = mstbanks;
	}

}
