package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mstlogin generated by hbm2java
 */
@Entity
@Table(name = "mstlogin", catalog = "dbschoolmanagementsystem")
public class Mstlogin implements java.io.Serializable {

	private Integer intLoginId;
	private Mstregistration mstregistration;
	private Integer txtRfid;
	private String txtPassword;
	private Date dtLastLoginDate;
	private Set<Tblstudstaffrecord> tblstudstaffrecords = new HashSet<Tblstudstaffrecord>(0);

	public Mstlogin() {
	}

	public Mstlogin(Mstregistration mstregistration, Integer txtRfid, String txtPassword, Date dtLastLoginDate,
			Set<Tblstudstaffrecord> tblstudstaffrecords) {
		this.mstregistration = mstregistration;
		this.txtRfid = txtRfid;
		this.txtPassword = txtPassword;
		this.dtLastLoginDate = dtLastLoginDate;
		this.tblstudstaffrecords = tblstudstaffrecords;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intLoginId", unique = true, nullable = false)
	public Integer getIntLoginId() {
		return this.intLoginId;
	}

	public void setIntLoginId(Integer intLoginId) {
		this.intLoginId = intLoginId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intRegistrationId")
	public Mstregistration getMstregistration() {
		return this.mstregistration;
	}

	public void setMstregistration(Mstregistration mstregistration) {
		this.mstregistration = mstregistration;
	}

	@Column(name = "txtRFID")
	public Integer getTxtRfid() {
		return this.txtRfid;
	}

	public void setTxtRfid(Integer txtRfid) {
		this.txtRfid = txtRfid;
	}

	@Column(name = "txtPassword", length = 50)
	public String getTxtPassword() {
		return this.txtPassword;
	}

	public void setTxtPassword(String txtPassword) {
		this.txtPassword = txtPassword;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dtLastLoginDate", length = 10)
	public Date getDtLastLoginDate() {
		return this.dtLastLoginDate;
	}

	public void setDtLastLoginDate(Date dtLastLoginDate) {
		this.dtLastLoginDate = dtLastLoginDate;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mstlogin")
	public Set<Tblstudstaffrecord> getTblstudstaffrecords() {
		return this.tblstudstaffrecords;
	}

	public void setTblstudstaffrecords(Set<Tblstudstaffrecord> tblstudstaffrecords) {
		this.tblstudstaffrecords = tblstudstaffrecords;
	}

}
