package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mstmaritalstatus generated by hbm2java
 */
@Entity
@Table(name = "mstmaritalstatus", catalog = "dbschoolmanagementsystem")
public class Mstmaritalstatus implements java.io.Serializable {

	private Integer intMaritalStatusId;
	private String txtMaritalStatus;
	private Set<Mstregistration> mstregistrations = new HashSet<Mstregistration>(0);

	public Mstmaritalstatus() {
	}

	public Mstmaritalstatus(String txtMaritalStatus, Set<Mstregistration> mstregistrations) {
		this.txtMaritalStatus = txtMaritalStatus;
		this.mstregistrations = mstregistrations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intMaritalStatusId", unique = true, nullable = false)
	public Integer getIntMaritalStatusId() {
		return this.intMaritalStatusId;
	}

	public void setIntMaritalStatusId(Integer intMaritalStatusId) {
		this.intMaritalStatusId = intMaritalStatusId;
	}

	@Column(name = "txtMaritalStatus", length = 50)
	public String getTxtMaritalStatus() {
		return this.txtMaritalStatus;
	}

	public void setTxtMaritalStatus(String txtMaritalStatus) {
		this.txtMaritalStatus = txtMaritalStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mstmaritalstatus")
	public Set<Mstregistration> getMstregistrations() {
		return this.mstregistrations;
	}

	public void setMstregistrations(Set<Mstregistration> mstregistrations) {
		this.mstregistrations = mstregistrations;
	}

}
