package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mstmothertongue generated by hbm2java
 */
@Entity
@Table(name = "mstmothertongue", catalog = "dbschoolmanagementsystem")
public class Mstmothertongue implements java.io.Serializable {

	private Integer intmothertongueId;
	private String txtmothertongue;
	private Set<Mstregistration> mstregistrations = new HashSet<Mstregistration>(0);

	public Mstmothertongue() {
	}

	public Mstmothertongue(String txtmothertongue, Set<Mstregistration> mstregistrations) {
		this.txtmothertongue = txtmothertongue;
		this.mstregistrations = mstregistrations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intmothertongueId", unique = true, nullable = false)
	public Integer getIntmothertongueId() {
		return this.intmothertongueId;
	}

	public void setIntmothertongueId(Integer intmothertongueId) {
		this.intmothertongueId = intmothertongueId;
	}

	@Column(name = "txtmothertongue", length = 50)
	public String getTxtmothertongue() {
		return this.txtmothertongue;
	}

	public void setTxtmothertongue(String txtmothertongue) {
		this.txtmothertongue = txtmothertongue;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mstmothertongue")
	public Set<Mstregistration> getMstregistrations() {
		return this.mstregistrations;
	}

	public void setMstregistrations(Set<Mstregistration> mstregistrations) {
		this.mstregistrations = mstregistrations;
	}

}
