package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mstmedium generated by hbm2java
 */
@Entity
@Table(name = "mstmedium", catalog = "dbschoolmanagementsystem")
public class Mstmedium implements java.io.Serializable {

	private Integer intMediumId;
	private String txtMedium;
	private Set<Mstregistration> mstregistrations = new HashSet<Mstregistration>(0);

	public Mstmedium() {
	}

	public Mstmedium(String txtMedium, Set<Mstregistration> mstregistrations) {
		this.txtMedium = txtMedium;
		this.mstregistrations = mstregistrations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intMediumId", unique = true, nullable = false)
	public Integer getIntMediumId() {
		return this.intMediumId;
	}

	public void setIntMediumId(Integer intMediumId) {
		this.intMediumId = intMediumId;
	}

	@Column(name = "txtMedium", length = 50)
	public String getTxtMedium() {
		return this.txtMedium;
	}

	public void setTxtMedium(String txtMedium) {
		this.txtMedium = txtMedium;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mstmedium")
	public Set<Mstregistration> getMstregistrations() {
		return this.mstregistrations;
	}

	public void setMstregistrations(Set<Mstregistration> mstregistrations) {
		this.mstregistrations = mstregistrations;
	}

}
