package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mstrelation generated by hbm2java
 */
@Entity
@Table(name = "mstrelation", catalog = "dbschoolmanagementsystem")
public class Mstrelation implements java.io.Serializable {

	private Integer intRelationId;
	private Mstgender mstgender;
	private String txtRelationType;

	public Mstrelation() {
	}

	public Mstrelation(Mstgender mstgender, String txtRelationType) {
		this.mstgender = mstgender;
		this.txtRelationType = txtRelationType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intRelationId", unique = true, nullable = false)
	public Integer getIntRelationId() {
		return this.intRelationId;
	}

	public void setIntRelationId(Integer intRelationId) {
		this.intRelationId = intRelationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intGenderId")
	public Mstgender getMstgender() {
		return this.mstgender;
	}

	public void setMstgender(Mstgender mstgender) {
		this.mstgender = mstgender;
	}

	@Column(name = "txtRelationType", length = 50)
	public String getTxtRelationType() {
		return this.txtRelationType;
	}

	public void setTxtRelationType(String txtRelationType) {
		this.txtRelationType = txtRelationType;
	}

}
