package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mstregistration generated by hbm2java
 */
@Entity
@Table(name = "mstregistration", catalog = "dbschoolmanagementsystem")
public class Mstregistration implements java.io.Serializable {

	private Integer intRegistrationId;
	private Mstaffiliation mstaffiliation;
	private Mstbloodgroup mstbloodgroup;
	private Mstcity mstcity;
	private Mstdisabilitychild mstdisabilitychild;
	private Mstgender mstgender;
	private Mstmaritalstatus mstmaritalstatus;
	private Mstmedium mstmedium;
	private Mstmothertongue mstmothertongue;
	private Mstreligion mstreligion;
	private Mstschooltype mstschooltype;
	private Mstsemester mstsemester;
	private Mstsocialcategory mstsocialcategory;
	private Mststream mststream;
	private Mststudclass mststudclass;
	private Mststudclasssection mststudclasssection;
	private Mstsubject mstsubject;
	private Tblrolename tblrolename;
	private String txtFirstName;
	private String txtMiddleName;
	private String txtLastName;
	private String txtEmailId;
	private Integer intReportingId;
	private String txtOriginalId;
	private String txtImagePath;
	private Integer intConfirmStatus;
	private Date dtJoiningDate;
	private Date dtDob;
	private Integer intIsActive;
	private String txtParentOccupation;
	private String txtDesignation;
	private String txtExperience;
	private String txtTransferCertificateNo;
	private Date dtTransferCertificateDate;
	private String txtPreviousSchoolName;
	private String txtPreviousSchoolAddress;
	private String txtFatherName;
	private String txtMotherName;
	private String txtFoccupation;
	private String txtMoccupation;
	private String txtFeducationalQualification;
	private String txtMeducationalQualification;
	private String txtFemailId;
	private String txtMemailId;
	private String txtFaadharNumber;
	private String txtMaadharNumber;
	private String txtNationality;
	private Long nmParentsAnnualIncome;
	private Integer intNoOfDependency;
	private String txtStudentCasteCertificateNo;
	private String txtStudentCaste;
	private String txtFathersCasteCertificateNo;
	private String txtFathersCaste;
	private String txtMothersCasteCertificateNo;
	private String txtMothersCaste;
	private Boolean blBelongToBpl;
	private String txtBplcardNo;
	private String txtLocality;
	private String txtTaluk;
	private String txtDistrict;
	private String txtPincode;
	private String txtStudentEnrollmentNumber;
	private Date dtAdmissionDate;
	private String txtPerAddress;
	private String txtTempAddress;
	private String txtFmobileNumber;
	private String txtMmobileNumber;
	private String txtFotherNumber;
	private String txtMotherNumber;
	private byte[] blImage;
	private Set<Mstfeemanagement> mstfeemanagements = new HashSet<Mstfeemanagement>(0);
	private Set<Mstquestionandanswer> mstquestionandanswers = new HashSet<Mstquestionandanswer>(0);
	private Set<Mststudclassgroup> mststudclassgroups = new HashSet<Mststudclassgroup>(0);
	private Set<Tbluserrole> tbluserroles = new HashSet<Tbluserrole>(0);
	private Set<Mstuploadstudmarksheet> mstuploadstudmarksheets = new HashSet<Mstuploadstudmarksheet>(0);
	private Set<Tblstudentperformance> tblstudentperformances = new HashSet<Tblstudentperformance>(0);
	private Set<Tblhomework> tblhomeworks = new HashSet<Tblhomework>(0);
	private Set<Trndocumentupload> trndocumentuploads = new HashSet<Trndocumentupload>(0);
	private Set<Mstlogin> mstlogins = new HashSet<Mstlogin>(0);
	private Set<Trnstudentleaveapp> trnstudentleaveapps = new HashSet<Trnstudentleaveapp>(0);
	private Set<Mstteacherinvite> mstteacherinvites = new HashSet<Mstteacherinvite>(0);
	private Set<Mstteacherproject> mstteacherprojects = new HashSet<Mstteacherproject>(0);
	private Set<Trnteacherleaveapp> trnteacherleaveapps = new HashSet<Trnteacherleaveapp>(0);
	private Set<Mstbank> mstbanks = new HashSet<Mstbank>(0);
	private Set<Mstteachertimetable> mstteachertimetables = new HashSet<Mstteachertimetable>(0);
	private Set<Trnattendancerecord> trnattendancerecords = new HashSet<Trnattendancerecord>(0);

	public Mstregistration() {
	}

	public Mstregistration(Mstaffiliation mstaffiliation, Mstbloodgroup mstbloodgroup, Mstcity mstcity,
			Mstdisabilitychild mstdisabilitychild, Mstgender mstgender, Mstmaritalstatus mstmaritalstatus,
			Mstmedium mstmedium, Mstmothertongue mstmothertongue, Mstreligion mstreligion, Mstschooltype mstschooltype,
			Mstsemester mstsemester, Mstsocialcategory mstsocialcategory, Mststream mststream,
			Mststudclass mststudclass, Mststudclasssection mststudclasssection, Mstsubject mstsubject,
			Tblrolename tblrolename, String txtFirstName, String txtMiddleName, String txtLastName, String txtEmailId,
			Integer intReportingId, String txtOriginalId, String txtImagePath, Integer intConfirmStatus,
			Date dtJoiningDate, Date dtDob, Integer intIsActive, String txtParentOccupation, String txtDesignation,
			String txtExperience, String txtTransferCertificateNo, Date dtTransferCertificateDate,
			String txtPreviousSchoolName, String txtPreviousSchoolAddress, String txtFatherName, String txtMotherName,
			String txtFoccupation, String txtMoccupation, String txtFeducationalQualification,
			String txtMeducationalQualification, String txtFemailId, String txtMemailId, String txtFaadharNumber,
			String txtMaadharNumber, String txtNationality, Long nmParentsAnnualIncome, Integer intNoOfDependency,
			String txtStudentCasteCertificateNo, String txtStudentCaste, String txtFathersCasteCertificateNo,
			String txtFathersCaste, String txtMothersCasteCertificateNo, String txtMothersCaste, Boolean blBelongToBpl,
			String txtBplcardNo, String txtLocality, String txtTaluk, String txtDistrict, String txtPincode,
			String txtStudentEnrollmentNumber, Date dtAdmissionDate, String txtPerAddress, String txtTempAddress,
			String txtFmobileNumber, String txtMmobileNumber, String txtFotherNumber, String txtMotherNumber,
			Set<Mstfeemanagement> mstfeemanagements, Set<Mstquestionandanswer> mstquestionandanswers,
			Set<Mststudclassgroup> mststudclassgroups, Set<Tbluserrole> tbluserroles,
			Set<Mstuploadstudmarksheet> mstuploadstudmarksheets, Set<Tblstudentperformance> tblstudentperformances,
			Set<Tblhomework> tblhomeworks, Set<Trndocumentupload> trndocumentuploads, Set<Mstlogin> mstlogins,
			Set<Trnstudentleaveapp> trnstudentleaveapps, Set<Mstteacherinvite> mstteacherinvites,
			Set<Mstteacherproject> mstteacherprojects, Set<Trnteacherleaveapp> trnteacherleaveapps,
			Set<Mstbank> mstbanks, Set<Mstteachertimetable> mstteachertimetables,
			Set<Trnattendancerecord> trnattendancerecords,byte[] blImage) {
		this.mstaffiliation = mstaffiliation;
		this.mstbloodgroup = mstbloodgroup;
		this.mstcity = mstcity;
		this.mstdisabilitychild = mstdisabilitychild;
		this.mstgender = mstgender;
		this.mstmaritalstatus = mstmaritalstatus;
		this.mstmedium = mstmedium;
		this.mstmothertongue = mstmothertongue;
		this.mstreligion = mstreligion;
		this.mstschooltype = mstschooltype;
		this.mstsemester = mstsemester;
		this.mstsocialcategory = mstsocialcategory;
		this.mststream = mststream;
		this.mststudclass = mststudclass;
		this.mststudclasssection = mststudclasssection;
		this.mstsubject = mstsubject;
		this.tblrolename = tblrolename;
		this.txtFirstName = txtFirstName;
		this.txtMiddleName = txtMiddleName;
		this.txtLastName = txtLastName;
		this.txtEmailId = txtEmailId;
		this.intReportingId = intReportingId;
		this.txtOriginalId = txtOriginalId;
		this.txtImagePath = txtImagePath;
		this.intConfirmStatus = intConfirmStatus;
		this.dtJoiningDate = dtJoiningDate;
		this.dtDob = dtDob;
		this.intIsActive = intIsActive;
		this.txtParentOccupation = txtParentOccupation;
		this.txtDesignation = txtDesignation;
		this.txtExperience = txtExperience;
		this.txtTransferCertificateNo = txtTransferCertificateNo;
		this.dtTransferCertificateDate = dtTransferCertificateDate;
		this.txtPreviousSchoolName = txtPreviousSchoolName;
		this.txtPreviousSchoolAddress = txtPreviousSchoolAddress;
		this.txtFatherName = txtFatherName;
		this.txtMotherName = txtMotherName;
		this.txtFoccupation = txtFoccupation;
		this.txtMoccupation = txtMoccupation;
		this.txtFeducationalQualification = txtFeducationalQualification;
		this.txtMeducationalQualification = txtMeducationalQualification;
		this.txtFemailId = txtFemailId;
		this.txtMemailId = txtMemailId;
		this.txtFaadharNumber = txtFaadharNumber;
		this.txtMaadharNumber = txtMaadharNumber;
		this.txtNationality = txtNationality;
		this.nmParentsAnnualIncome = nmParentsAnnualIncome;
		this.intNoOfDependency = intNoOfDependency;
		this.txtStudentCasteCertificateNo = txtStudentCasteCertificateNo;
		this.txtStudentCaste = txtStudentCaste;
		this.txtFathersCasteCertificateNo = txtFathersCasteCertificateNo;
		this.txtFathersCaste = txtFathersCaste;
		this.txtMothersCasteCertificateNo = txtMothersCasteCertificateNo;
		this.txtMothersCaste = txtMothersCaste;
		this.blBelongToBpl = blBelongToBpl;
		this.txtBplcardNo = txtBplcardNo;
		this.txtLocality = txtLocality;
		this.txtTaluk = txtTaluk;
		this.txtDistrict = txtDistrict;
		this.txtPincode = txtPincode;
		this.txtStudentEnrollmentNumber = txtStudentEnrollmentNumber;
		this.dtAdmissionDate = dtAdmissionDate;
		this.txtPerAddress = txtPerAddress;
		this.txtTempAddress = txtTempAddress;
		this.txtFmobileNumber = txtFmobileNumber;
		this.txtMmobileNumber = txtMmobileNumber;
		this.txtFotherNumber = txtFotherNumber;
		this.txtMotherNumber = txtMotherNumber;
		this.mstfeemanagements = mstfeemanagements;
		this.mstquestionandanswers = mstquestionandanswers;
		this.mststudclassgroups = mststudclassgroups;
		this.tbluserroles = tbluserroles;
		this.mstuploadstudmarksheets = mstuploadstudmarksheets;
		this.tblstudentperformances = tblstudentperformances;
		this.tblhomeworks = tblhomeworks;
		this.trndocumentuploads = trndocumentuploads;
		this.mstlogins = mstlogins;
		this.trnstudentleaveapps = trnstudentleaveapps;
		this.mstteacherinvites = mstteacherinvites;
		this.mstteacherprojects = mstteacherprojects;
		this.trnteacherleaveapps = trnteacherleaveapps;
		this.mstbanks = mstbanks;
		this.mstteachertimetables = mstteachertimetables;
		this.trnattendancerecords = trnattendancerecords;
		this.blImage = blImage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intRegistrationId", unique = true, nullable = false)
	public Integer getIntRegistrationId() {
		return this.intRegistrationId;
	}

	public void setIntRegistrationId(Integer intRegistrationId) {
		this.intRegistrationId = intRegistrationId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intAffiliationId")
	public Mstaffiliation getMstaffiliation() {
		return this.mstaffiliation;
	}

	public void setMstaffiliation(Mstaffiliation mstaffiliation) {
		this.mstaffiliation = mstaffiliation;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intBloodGroupId")
	public Mstbloodgroup getMstbloodgroup() {
		return this.mstbloodgroup;
	}

	public void setMstbloodgroup(Mstbloodgroup mstbloodgroup) {
		this.mstbloodgroup = mstbloodgroup;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intCityId")
	public Mstcity getMstcity() {
		return this.mstcity;
	}

	public void setMstcity(Mstcity mstcity) {
		this.mstcity = mstcity;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intDisabilityChildId")
	public Mstdisabilitychild getMstdisabilitychild() {
		return this.mstdisabilitychild;
	}

	public void setMstdisabilitychild(Mstdisabilitychild mstdisabilitychild) {
		this.mstdisabilitychild = mstdisabilitychild;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intGenderId")
	public Mstgender getMstgender() {
		return this.mstgender;
	}

	public void setMstgender(Mstgender mstgender) {
		this.mstgender = mstgender;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intMaritalStatusId")
	public Mstmaritalstatus getMstmaritalstatus() {
		return this.mstmaritalstatus;
	}

	public void setMstmaritalstatus(Mstmaritalstatus mstmaritalstatus) {
		this.mstmaritalstatus = mstmaritalstatus;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intMediumId")
	public Mstmedium getMstmedium() {
		return this.mstmedium;
	}

	public void setMstmedium(Mstmedium mstmedium) {
		this.mstmedium = mstmedium;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intmothertongueId")
	public Mstmothertongue getMstmothertongue() {
		return this.mstmothertongue;
	}

	public void setMstmothertongue(Mstmothertongue mstmothertongue) {
		this.mstmothertongue = mstmothertongue;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intReligionId")
	public Mstreligion getMstreligion() {
		return this.mstreligion;
	}

	public void setMstreligion(Mstreligion mstreligion) {
		this.mstreligion = mstreligion;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intSchoolTypeId")
	public Mstschooltype getMstschooltype() {
		return this.mstschooltype;
	}

	public void setMstschooltype(Mstschooltype mstschooltype) {
		this.mstschooltype = mstschooltype;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intSemesterId")
	public Mstsemester getMstsemester() {
		return this.mstsemester;
	}

	public void setMstsemester(Mstsemester mstsemester) {
		this.mstsemester = mstsemester;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intSocialCategoryId")
	public Mstsocialcategory getMstsocialcategory() {
		return this.mstsocialcategory;
	}

	public void setMstsocialcategory(Mstsocialcategory mstsocialcategory) {
		this.mstsocialcategory = mstsocialcategory;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intStreamId")
	public Mststream getMststream() {
		return this.mststream;
	}

	public void setMststream(Mststream mststream) {
		this.mststream = mststream;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intClassId")
	public Mststudclass getMststudclass() {
		return this.mststudclass;
	}

	public void setMststudclass(Mststudclass mststudclass) {
		this.mststudclass = mststudclass;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intSectionId")
	public Mststudclasssection getMststudclasssection() {
		return this.mststudclasssection;
	}

	public void setMststudclasssection(Mststudclasssection mststudclasssection) {
		this.mststudclasssection = mststudclasssection;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intSubjectId")
	public Mstsubject getMstsubject() {
		return this.mstsubject;
	}

	public void setMstsubject(Mstsubject mstsubject) {
		this.mstsubject = mstsubject;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intRoleId")
	public Tblrolename getTblrolename() {
		return this.tblrolename;
	}

	public void setTblrolename(Tblrolename tblrolename) {
		this.tblrolename = tblrolename;
	}

	@Column(name = "txtFirstName", length = 50)
	public String getTxtFirstName() {
		return this.txtFirstName;
	}

	public void setTxtFirstName(String txtFirstName) {
		this.txtFirstName = txtFirstName;
	}

	@Column(name = "txtMiddleName", length = 50)
	public String getTxtMiddleName() {
		return this.txtMiddleName;
	}

	public void setTxtMiddleName(String txtMiddleName) {
		this.txtMiddleName = txtMiddleName;
	}

	@Column(name = "txtLastName", length = 50)
	public String getTxtLastName() {
		return this.txtLastName;
	}

	public void setTxtLastName(String txtLastName) {
		this.txtLastName = txtLastName;
	}

	@Column(name = "txtEmailId", length = 50)
	public String getTxtEmailId() {
		return this.txtEmailId;
	}

	public void setTxtEmailId(String txtEmailId) {
		this.txtEmailId = txtEmailId;
	}

	@Column(name = "intReportingId")
	public Integer getIntReportingId() {
		return this.intReportingId;
	}

	public void setIntReportingId(Integer intReportingId) {
		this.intReportingId = intReportingId;
	}

	@Column(name = "txtOriginalId", length = 50)
	public String getTxtOriginalId() {
		return this.txtOriginalId;
	}

	public void setTxtOriginalId(String txtOriginalId) {
		this.txtOriginalId = txtOriginalId;
	}

	@Column(name = "txtImagePath", length = 50)
	public String getTxtImagePath() {
		return this.txtImagePath;
	}

	public void setTxtImagePath(String txtImagePath) {
		this.txtImagePath = txtImagePath;
	}

	@Column(name = "intConfirmStatus")
	public Integer getIntConfirmStatus() {
		return this.intConfirmStatus;
	}

	public void setIntConfirmStatus(Integer intConfirmStatus) {
		this.intConfirmStatus = intConfirmStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dtJoiningDate", length = 10)
	public Date getDtJoiningDate() {
		return this.dtJoiningDate;
	}

	public void setDtJoiningDate(Date dtJoiningDate) {
		this.dtJoiningDate = dtJoiningDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dtDOB", length = 10)
	public Date getDtDob() {
		return this.dtDob;
	}

	public void setDtDob(Date dtDob) {
		this.dtDob = dtDob;
	}

	@Column(name = "intIsActive")
	public Integer getIntIsActive() {
		return this.intIsActive;
	}

	public void setIntIsActive(Integer intIsActive) {
		this.intIsActive = intIsActive;
	}

	@Column(name = "txtParentOccupation", length = 50)
	public String getTxtParentOccupation() {
		return this.txtParentOccupation;
	}

	public void setTxtParentOccupation(String txtParentOccupation) {
		this.txtParentOccupation = txtParentOccupation;
	}

	@Column(name = "txtDesignation", length = 50)
	public String getTxtDesignation() {
		return this.txtDesignation;
	}

	public void setTxtDesignation(String txtDesignation) {
		this.txtDesignation = txtDesignation;
	}

	@Column(name = "txtExperience", length = 50)
	public String getTxtExperience() {
		return this.txtExperience;
	}

	public void setTxtExperience(String txtExperience) {
		this.txtExperience = txtExperience;
	}

	@Column(name = "txtTransferCertificateNo", length = 11)
	public String getTxtTransferCertificateNo() {
		return this.txtTransferCertificateNo;
	}

	public void setTxtTransferCertificateNo(String txtTransferCertificateNo) {
		this.txtTransferCertificateNo = txtTransferCertificateNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dtTransferCertificateDate", length = 10)
	public Date getDtTransferCertificateDate() {
		return this.dtTransferCertificateDate;
	}

	public void setDtTransferCertificateDate(Date dtTransferCertificateDate) {
		this.dtTransferCertificateDate = dtTransferCertificateDate;
	}

	@Column(name = "txtPreviousSchoolName", length = 200)
	public String getTxtPreviousSchoolName() {
		return this.txtPreviousSchoolName;
	}

	public void setTxtPreviousSchoolName(String txtPreviousSchoolName) {
		this.txtPreviousSchoolName = txtPreviousSchoolName;
	}

	@Column(name = "txtPreviousSchoolAddress", length = 200)
	public String getTxtPreviousSchoolAddress() {
		return this.txtPreviousSchoolAddress;
	}

	public void setTxtPreviousSchoolAddress(String txtPreviousSchoolAddress) {
		this.txtPreviousSchoolAddress = txtPreviousSchoolAddress;
	}

	@Column(name = "txtFatherName", length = 50)
	public String getTxtFatherName() {
		return this.txtFatherName;
	}

	public void setTxtFatherName(String txtFatherName) {
		this.txtFatherName = txtFatherName;
	}

	@Column(name = "txtMotherName", length = 50)
	public String getTxtMotherName() {
		return this.txtMotherName;
	}

	public void setTxtMotherName(String txtMotherName) {
		this.txtMotherName = txtMotherName;
	}

	@Column(name = "txtFOccupation", length = 50)
	public String getTxtFoccupation() {
		return this.txtFoccupation;
	}

	public void setTxtFoccupation(String txtFoccupation) {
		this.txtFoccupation = txtFoccupation;
	}

	@Column(name = "txtMOccupation", length = 50)
	public String getTxtMoccupation() {
		return this.txtMoccupation;
	}

	public void setTxtMoccupation(String txtMoccupation) {
		this.txtMoccupation = txtMoccupation;
	}

	@Column(name = "txtFEducationalQualification", length = 50)
	public String getTxtFeducationalQualification() {
		return this.txtFeducationalQualification;
	}

	public void setTxtFeducationalQualification(String txtFeducationalQualification) {
		this.txtFeducationalQualification = txtFeducationalQualification;
	}

	@Column(name = "txtMEducationalQualification", length = 50)
	public String getTxtMeducationalQualification() {
		return this.txtMeducationalQualification;
	}

	public void setTxtMeducationalQualification(String txtMeducationalQualification) {
		this.txtMeducationalQualification = txtMeducationalQualification;
	}

	@Column(name = "txtFEmailId", length = 50)
	public String getTxtFemailId() {
		return this.txtFemailId;
	}

	public void setTxtFemailId(String txtFemailId) {
		this.txtFemailId = txtFemailId;
	}

	@Column(name = "txtMEmailId", length = 50)
	public String getTxtMemailId() {
		return this.txtMemailId;
	}

	public void setTxtMemailId(String txtMemailId) {
		this.txtMemailId = txtMemailId;
	}

	@Column(name = "txtFAadharNumber", length = 50)
	public String getTxtFaadharNumber() {
		return this.txtFaadharNumber;
	}

	public void setTxtFaadharNumber(String txtFaadharNumber) {
		this.txtFaadharNumber = txtFaadharNumber;
	}

	@Column(name = "txtMAadharNumber", length = 50)
	public String getTxtMaadharNumber() {
		return this.txtMaadharNumber;
	}

	public void setTxtMaadharNumber(String txtMaadharNumber) {
		this.txtMaadharNumber = txtMaadharNumber;
	}

	@Column(name = "txtNationality", length = 50)
	public String getTxtNationality() {
		return this.txtNationality;
	}

	public void setTxtNationality(String txtNationality) {
		this.txtNationality = txtNationality;
	}

	@Column(name = "nmParentsAnnualIncome", precision = 10, scale = 0)
	public Long getNmParentsAnnualIncome() {
		return this.nmParentsAnnualIncome;
	}

	public void setNmParentsAnnualIncome(Long nmParentsAnnualIncome) {
		this.nmParentsAnnualIncome = nmParentsAnnualIncome;
	}

	@Column(name = "intNoOfDependency")
	public Integer getIntNoOfDependency() {
		return this.intNoOfDependency;
	}

	public void setIntNoOfDependency(Integer intNoOfDependency) {
		this.intNoOfDependency = intNoOfDependency;
	}

	@Column(name = "txtStudentCasteCertificateNo", length = 50)
	public String getTxtStudentCasteCertificateNo() {
		return this.txtStudentCasteCertificateNo;
	}

	public void setTxtStudentCasteCertificateNo(String txtStudentCasteCertificateNo) {
		this.txtStudentCasteCertificateNo = txtStudentCasteCertificateNo;
	}

	@Column(name = "txtStudentCaste", length = 50)
	public String getTxtStudentCaste() {
		return this.txtStudentCaste;
	}

	public void setTxtStudentCaste(String txtStudentCaste) {
		this.txtStudentCaste = txtStudentCaste;
	}

	@Column(name = "txtFathersCasteCertificateNo", length = 50)
	public String getTxtFathersCasteCertificateNo() {
		return this.txtFathersCasteCertificateNo;
	}

	public void setTxtFathersCasteCertificateNo(String txtFathersCasteCertificateNo) {
		this.txtFathersCasteCertificateNo = txtFathersCasteCertificateNo;
	}

	@Column(name = "txtFathersCaste", length = 50)
	public String getTxtFathersCaste() {
		return this.txtFathersCaste;
	}

	public void setTxtFathersCaste(String txtFathersCaste) {
		this.txtFathersCaste = txtFathersCaste;
	}

	@Column(name = "txtMothersCasteCertificateNo", length = 50)
	public String getTxtMothersCasteCertificateNo() {
		return this.txtMothersCasteCertificateNo;
	}

	public void setTxtMothersCasteCertificateNo(String txtMothersCasteCertificateNo) {
		this.txtMothersCasteCertificateNo = txtMothersCasteCertificateNo;
	}

	@Column(name = "txtMothersCaste", length = 50)
	public String getTxtMothersCaste() {
		return this.txtMothersCaste;
	}

	public void setTxtMothersCaste(String txtMothersCaste) {
		this.txtMothersCaste = txtMothersCaste;
	}

	@Column(name = "blBelongToBPL")
	public Boolean getBlBelongToBpl() {
		return this.blBelongToBpl;
	}

	public void setBlBelongToBpl(Boolean blBelongToBpl) {
		this.blBelongToBpl = blBelongToBpl;
	}

	@Column(name = "txtBPLCardNo", length = 50)
	public String getTxtBplcardNo() {
		return this.txtBplcardNo;
	}

	public void setTxtBplcardNo(String txtBplcardNo) {
		this.txtBplcardNo = txtBplcardNo;
	}

	@Column(name = "txtLocality", length = 50)
	public String getTxtLocality() {
		return this.txtLocality;
	}

	public void setTxtLocality(String txtLocality) {
		this.txtLocality = txtLocality;
	}

	@Column(name = "txtTaluk", length = 50)
	public String getTxtTaluk() {
		return this.txtTaluk;
	}

	public void setTxtTaluk(String txtTaluk) {
		this.txtTaluk = txtTaluk;
	}

	@Column(name = "txtDistrict", length = 50)
	public String getTxtDistrict() {
		return this.txtDistrict;
	}

	public void setTxtDistrict(String txtDistrict) {
		this.txtDistrict = txtDistrict;
	}

	@Column(name = "txtPincode", length = 20)
	public String getTxtPincode() {
		return this.txtPincode;
	}

	public void setTxtPincode(String txtPincode) {
		this.txtPincode = txtPincode;
	}

	@Column(name = "txtStudentEnrollmentNumber", length = 50)
	public String getTxtStudentEnrollmentNumber() {
		return this.txtStudentEnrollmentNumber;
	}

	public void setTxtStudentEnrollmentNumber(String txtStudentEnrollmentNumber) {
		this.txtStudentEnrollmentNumber = txtStudentEnrollmentNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dtAdmissionDate", length = 10)
	public Date getDtAdmissionDate() {
		return this.dtAdmissionDate;
	}

	public void setDtAdmissionDate(Date dtAdmissionDate) {
		this.dtAdmissionDate = dtAdmissionDate;
	}

	@Column(name = "txtPerAddress", length = 200)
	public String getTxtPerAddress() {
		return this.txtPerAddress;
	}

	public void setTxtPerAddress(String txtPerAddress) {
		this.txtPerAddress = txtPerAddress;
	}

	@Column(name = "txtTempAddress", length = 200)
	public String getTxtTempAddress() {
		return this.txtTempAddress;
	}

	public void setTxtTempAddress(String txtTempAddress) {
		this.txtTempAddress = txtTempAddress;
	}

	@Column(name = "txtFMobileNumber", length = 50)
	public String getTxtFmobileNumber() {
		return this.txtFmobileNumber;
	}

	public void setTxtFmobileNumber(String txtFmobileNumber) {
		this.txtFmobileNumber = txtFmobileNumber;
	}

	@Column(name = "txtMMobileNumber", length = 50)
	public String getTxtMmobileNumber() {
		return this.txtMmobileNumber;
	}

	public void setTxtMmobileNumber(String txtMmobileNumber) {
		this.txtMmobileNumber = txtMmobileNumber;
	}

	@Column(name = "txtFOtherNumber", length = 50)
	public String getTxtFotherNumber() {
		return this.txtFotherNumber;
	}

	public void setTxtFotherNumber(String txtFotherNumber) {
		this.txtFotherNumber = txtFotherNumber;
	}

	@Column(name = "txtMOtherNumber", length = 50)
	public String getTxtMotherNumber() {
		return this.txtMotherNumber;
	}

	public void setTxtMotherNumber(String txtMotherNumber) {
		this.txtMotherNumber = txtMotherNumber;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mstregistration")
	public Set<Mstfeemanagement> getMstfeemanagements() {
		return this.mstfeemanagements;
	}

	public void setMstfeemanagements(Set<Mstfeemanagement> mstfeemanagements) {
		this.mstfeemanagements = mstfeemanagements;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mstregistration")
	public Set<Mstquestionandanswer> getMstquestionandanswers() {
		return this.mstquestionandanswers;
	}

	public void setMstquestionandanswers(Set<Mstquestionandanswer> mstquestionandanswers) {
		this.mstquestionandanswers = mstquestionandanswers;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mstregistration")
	public Set<Mststudclassgroup> getMststudclassgroups() {
		return this.mststudclassgroups;
	}

	public void setMststudclassgroups(Set<Mststudclassgroup> mststudclassgroups) {
		this.mststudclassgroups = mststudclassgroups;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mstregistration")
	public Set<Tbluserrole> getTbluserroles() {
		return this.tbluserroles;
	}

	public void setTbluserroles(Set<Tbluserrole> tbluserroles) {
		this.tbluserroles = tbluserroles;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mstregistration")
	public Set<Mstuploadstudmarksheet> getMstuploadstudmarksheets() {
		return this.mstuploadstudmarksheets;
	}

	public void setMstuploadstudmarksheets(Set<Mstuploadstudmarksheet> mstuploadstudmarksheets) {
		this.mstuploadstudmarksheets = mstuploadstudmarksheets;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mstregistration")
	public Set<Tblstudentperformance> getTblstudentperformances() {
		return this.tblstudentperformances;
	}

	public void setTblstudentperformances(Set<Tblstudentperformance> tblstudentperformances) {
		this.tblstudentperformances = tblstudentperformances;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mstregistration")
	public Set<Tblhomework> getTblhomeworks() {
		return this.tblhomeworks;
	}

	public void setTblhomeworks(Set<Tblhomework> tblhomeworks) {
		this.tblhomeworks = tblhomeworks;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mstregistration")
	public Set<Trndocumentupload> getTrndocumentuploads() {
		return this.trndocumentuploads;
	}

	public void setTrndocumentuploads(Set<Trndocumentupload> trndocumentuploads) {
		this.trndocumentuploads = trndocumentuploads;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mstregistration")
	public Set<Mstlogin> getMstlogins() {
		return this.mstlogins;
	}

	public void setMstlogins(Set<Mstlogin> mstlogins) {
		this.mstlogins = mstlogins;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mstregistration")
	public Set<Trnstudentleaveapp> getTrnstudentleaveapps() {
		return this.trnstudentleaveapps;
	}

	public void setTrnstudentleaveapps(Set<Trnstudentleaveapp> trnstudentleaveapps) {
		this.trnstudentleaveapps = trnstudentleaveapps;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mstregistration")
	public Set<Mstteacherinvite> getMstteacherinvites() {
		return this.mstteacherinvites;
	}

	public void setMstteacherinvites(Set<Mstteacherinvite> mstteacherinvites) {
		this.mstteacherinvites = mstteacherinvites;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mstregistration")
	public Set<Mstteacherproject> getMstteacherprojects() {
		return this.mstteacherprojects;
	}

	public void setMstteacherprojects(Set<Mstteacherproject> mstteacherprojects) {
		this.mstteacherprojects = mstteacherprojects;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mstregistration")
	public Set<Trnteacherleaveapp> getTrnteacherleaveapps() {
		return this.trnteacherleaveapps;
	}

	public void setTrnteacherleaveapps(Set<Trnteacherleaveapp> trnteacherleaveapps) {
		this.trnteacherleaveapps = trnteacherleaveapps;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mstregistration")
	public Set<Mstbank> getMstbanks() {
		return this.mstbanks;
	}

	public void setMstbanks(Set<Mstbank> mstbanks) {
		this.mstbanks = mstbanks;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mstregistration")
	public Set<Mstteachertimetable> getMstteachertimetables() {
		return this.mstteachertimetables;
	}

	public void setMstteachertimetables(Set<Mstteachertimetable> mstteachertimetables) {
		this.mstteachertimetables = mstteachertimetables;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mstregistration")
	public Set<Trnattendancerecord> getTrnattendancerecords() {
		return this.trnattendancerecords;
	}

	public void setTrnattendancerecords(Set<Trnattendancerecord> trnattendancerecords) {
		this.trnattendancerecords = trnattendancerecords;
	}
	@Column(name = "blImage")
	public byte[] getBlImage() {
		return blImage;
	}

	public void setBlImage(byte[] blImage) {
		this.blImage = blImage;
	}
	
	

}
