package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mstsubcategory generated by hbm2java
 */
@Entity
@Table(name = "mstsubcategory", catalog = "dbschoolmanagementsystem")
public class Mstsubcategory implements java.io.Serializable {

	private Integer intSubCategoryId;
	private String txtSubCategoryName;
	private Set<Mstdocumentsupload> mstdocumentsuploads = new HashSet<Mstdocumentsupload>(0);
	private Set<Trndocumentupload> trndocumentuploads = new HashSet<Trndocumentupload>(0);

	public Mstsubcategory() {
	}

	public Mstsubcategory(String txtSubCategoryName, Set<Mstdocumentsupload> mstdocumentsuploads,
			Set<Trndocumentupload> trndocumentuploads) {
		this.txtSubCategoryName = txtSubCategoryName;
		this.mstdocumentsuploads = mstdocumentsuploads;
		this.trndocumentuploads = trndocumentuploads;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intSubCategoryId", unique = true, nullable = false)
	public Integer getIntSubCategoryId() {
		return this.intSubCategoryId;
	}

	public void setIntSubCategoryId(Integer intSubCategoryId) {
		this.intSubCategoryId = intSubCategoryId;
	}

	@Column(name = "txtSubCategoryName", length = 50)
	public String getTxtSubCategoryName() {
		return this.txtSubCategoryName;
	}

	public void setTxtSubCategoryName(String txtSubCategoryName) {
		this.txtSubCategoryName = txtSubCategoryName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mstsubcategory")
	public Set<Mstdocumentsupload> getMstdocumentsuploads() {
		return this.mstdocumentsuploads;
	}

	public void setMstdocumentsuploads(Set<Mstdocumentsupload> mstdocumentsuploads) {
		this.mstdocumentsuploads = mstdocumentsuploads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mstsubcategory")
	public Set<Trndocumentupload> getTrndocumentuploads() {
		return this.trndocumentuploads;
	}

	public void setTrndocumentuploads(Set<Trndocumentupload> trndocumentuploads) {
		this.trndocumentuploads = trndocumentuploads;
	}

}
