package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mststudclasssection generated by hbm2java
 */
@Entity
@Table(name = "mststudclasssection", catalog = "dbschoolmanagementsystem")
public class Mststudclasssection implements java.io.Serializable {

	private Integer intSectionId;
	private Mststudclass mststudclass;
	private String txtSectionName;
	private Integer intStatus;
	private Integer intNoOfStudents;
	private Set<Mstteacherinvite> mstteacherinvites = new HashSet<Mstteacherinvite>(0);
	private Set<Tblinvites> tblinviteses = new HashSet<Tblinvites>(0);
	private Set<Tblhomework> tblhomeworks = new HashSet<Tblhomework>(0);
	private Set<Mstfeemanagement> mstfeemanagements = new HashSet<Mstfeemanagement>(0);
	private Set<Tblstudstaffrecord> tblstudstaffrecords = new HashSet<Tblstudstaffrecord>(0);
	private Set<Mstteacherproject> mstteacherprojects = new HashSet<Mstteacherproject>(0);
	private Set<Mstuploadstudmarksheet> mstuploadstudmarksheets = new HashSet<Mstuploadstudmarksheet>(0);
	private Set<Tblstudentperformance> tblstudentperformances = new HashSet<Tblstudentperformance>(0);
	private Set<Mstregistration> mstregistrations = new HashSet<Mstregistration>(0);
	private Set<Mststudclassgroup> mststudclassgroups = new HashSet<Mststudclassgroup>(0);
	private Set<Mststudenttimetable> mststudenttimetables = new HashSet<Mststudenttimetable>(0);
	private Set<Mstteachertimetable> mstteachertimetables = new HashSet<Mstteachertimetable>(0);

	public Mststudclasssection() {
	}

	public Mststudclasssection(Mststudclass mststudclass, String txtSectionName, Integer intStatus,
			Integer intNoOfStudents, Set<Mstteacherinvite> mstteacherinvites, Set<Tblinvites> tblinviteses,
			Set<Tblhomework> tblhomeworks, Set<Mstfeemanagement> mstfeemanagements,
			Set<Tblstudstaffrecord> tblstudstaffrecords, Set<Mstteacherproject> mstteacherprojects,
			Set<Mstuploadstudmarksheet> mstuploadstudmarksheets, Set<Tblstudentperformance> tblstudentperformances,
			Set<Mstregistration> mstregistrations, Set<Mststudclassgroup> mststudclassgroups,
			Set<Mststudenttimetable> mststudenttimetables, Set<Mstteachertimetable> mstteachertimetables) {
		this.mststudclass = mststudclass;
		this.txtSectionName = txtSectionName;
		this.intStatus = intStatus;
		this.intNoOfStudents = intNoOfStudents;
		this.mstteacherinvites = mstteacherinvites;
		this.tblinviteses = tblinviteses;
		this.tblhomeworks = tblhomeworks;
		this.mstfeemanagements = mstfeemanagements;
		this.tblstudstaffrecords = tblstudstaffrecords;
		this.mstteacherprojects = mstteacherprojects;
		this.mstuploadstudmarksheets = mstuploadstudmarksheets;
		this.tblstudentperformances = tblstudentperformances;
		this.mstregistrations = mstregistrations;
		this.mststudclassgroups = mststudclassgroups;
		this.mststudenttimetables = mststudenttimetables;
		this.mstteachertimetables = mstteachertimetables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intSectionId", unique = true, nullable = false)
	public Integer getIntSectionId() {
		return this.intSectionId;
	}

	public void setIntSectionId(Integer intSectionId) {
		this.intSectionId = intSectionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intClassId")
	public Mststudclass getMststudclass() {
		return this.mststudclass;
	}

	public void setMststudclass(Mststudclass mststudclass) {
		this.mststudclass = mststudclass;
	}

	@Column(name = "txtSectionName", length = 50)
	public String getTxtSectionName() {
		return this.txtSectionName;
	}

	public void setTxtSectionName(String txtSectionName) {
		this.txtSectionName = txtSectionName;
	}

	@Column(name = "intStatus")
	public Integer getIntStatus() {
		return this.intStatus;
	}

	public void setIntStatus(Integer intStatus) {
		this.intStatus = intStatus;
	}

	@Column(name = "intNoOfStudents")
	public Integer getIntNoOfStudents() {
		return this.intNoOfStudents;
	}

	public void setIntNoOfStudents(Integer intNoOfStudents) {
		this.intNoOfStudents = intNoOfStudents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mststudclasssection")
	public Set<Mstteacherinvite> getMstteacherinvites() {
		return this.mstteacherinvites;
	}

	public void setMstteacherinvites(Set<Mstteacherinvite> mstteacherinvites) {
		this.mstteacherinvites = mstteacherinvites;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mststudclasssection")
	public Set<Tblinvites> getTblinviteses() {
		return this.tblinviteses;
	}

	public void setTblinviteses(Set<Tblinvites> tblinviteses) {
		this.tblinviteses = tblinviteses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mststudclasssection")
	public Set<Tblhomework> getTblhomeworks() {
		return this.tblhomeworks;
	}

	public void setTblhomeworks(Set<Tblhomework> tblhomeworks) {
		this.tblhomeworks = tblhomeworks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mststudclasssection")
	public Set<Mstfeemanagement> getMstfeemanagements() {
		return this.mstfeemanagements;
	}

	public void setMstfeemanagements(Set<Mstfeemanagement> mstfeemanagements) {
		this.mstfeemanagements = mstfeemanagements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mststudclasssection")
	public Set<Tblstudstaffrecord> getTblstudstaffrecords() {
		return this.tblstudstaffrecords;
	}

	public void setTblstudstaffrecords(Set<Tblstudstaffrecord> tblstudstaffrecords) {
		this.tblstudstaffrecords = tblstudstaffrecords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mststudclasssection")
	public Set<Mstteacherproject> getMstteacherprojects() {
		return this.mstteacherprojects;
	}

	public void setMstteacherprojects(Set<Mstteacherproject> mstteacherprojects) {
		this.mstteacherprojects = mstteacherprojects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mststudclasssection")
	public Set<Mstuploadstudmarksheet> getMstuploadstudmarksheets() {
		return this.mstuploadstudmarksheets;
	}

	public void setMstuploadstudmarksheets(Set<Mstuploadstudmarksheet> mstuploadstudmarksheets) {
		this.mstuploadstudmarksheets = mstuploadstudmarksheets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mststudclasssection")
	public Set<Tblstudentperformance> getTblstudentperformances() {
		return this.tblstudentperformances;
	}

	public void setTblstudentperformances(Set<Tblstudentperformance> tblstudentperformances) {
		this.tblstudentperformances = tblstudentperformances;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mststudclasssection")
	public Set<Mstregistration> getMstregistrations() {
		return this.mstregistrations;
	}

	public void setMstregistrations(Set<Mstregistration> mstregistrations) {
		this.mstregistrations = mstregistrations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mststudclasssection")
	public Set<Mststudclassgroup> getMststudclassgroups() {
		return this.mststudclassgroups;
	}

	public void setMststudclassgroups(Set<Mststudclassgroup> mststudclassgroups) {
		this.mststudclassgroups = mststudclassgroups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mststudclasssection")
	public Set<Mststudenttimetable> getMststudenttimetables() {
		return this.mststudenttimetables;
	}

	public void setMststudenttimetables(Set<Mststudenttimetable> mststudenttimetables) {
		this.mststudenttimetables = mststudenttimetables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mststudclasssection")
	public Set<Mstteachertimetable> getMstteachertimetables() {
		return this.mstteachertimetables;
	}

	public void setMstteachertimetables(Set<Mstteachertimetable> mstteachertimetables) {
		this.mstteachertimetables = mstteachertimetables;
	}

}
