package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mstschooltype generated by hbm2java
 */
@Entity
@Table(name = "mstschooltype", catalog = "dbschoolmanagementsystem")
public class Mstschooltype implements java.io.Serializable {

	private Integer intSchoolTypeId;
	private String txtSchoolType;
	private Set<Mstregistration> mstregistrations = new HashSet<Mstregistration>(0);

	public Mstschooltype() {
	}

	public Mstschooltype(String txtSchoolType, Set<Mstregistration> mstregistrations) {
		this.txtSchoolType = txtSchoolType;
		this.mstregistrations = mstregistrations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intSchoolTypeId", unique = true, nullable = false)
	public Integer getIntSchoolTypeId() {
		return this.intSchoolTypeId;
	}

	public void setIntSchoolTypeId(Integer intSchoolTypeId) {
		this.intSchoolTypeId = intSchoolTypeId;
	}

	@Column(name = "txtSchoolType", length = 50)
	public String getTxtSchoolType() {
		return this.txtSchoolType;
	}

	public void setTxtSchoolType(String txtSchoolType) {
		this.txtSchoolType = txtSchoolType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mstschooltype")
	public Set<Mstregistration> getMstregistrations() {
		return this.mstregistrations;
	}

	public void setMstregistrations(Set<Mstregistration> mstregistrations) {
		this.mstregistrations = mstregistrations;
	}

}
