package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mstsemester generated by hbm2java
 */
@Entity
@Table(name = "mstsemester", catalog = "dbschoolmanagementsystem")
public class Mstsemester implements java.io.Serializable {

	private Integer intSemesterId;
	private String txtSemester;
	private Set<Mstregistration> mstregistrations = new HashSet<Mstregistration>(0);

	public Mstsemester() {
	}

	public Mstsemester(String txtSemester, Set<Mstregistration> mstregistrations) {
		this.txtSemester = txtSemester;
		this.mstregistrations = mstregistrations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intSemesterId", unique = true, nullable = false)
	public Integer getIntSemesterId() {
		return this.intSemesterId;
	}

	public void setIntSemesterId(Integer intSemesterId) {
		this.intSemesterId = intSemesterId;
	}

	@Column(name = "txtSemester", length = 50)
	public String getTxtSemester() {
		return this.txtSemester;
	}

	public void setTxtSemester(String txtSemester) {
		this.txtSemester = txtSemester;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mstsemester")
	public Set<Mstregistration> getMstregistrations() {
		return this.mstregistrations;
	}

	public void setMstregistrations(Set<Mstregistration> mstregistrations) {
		this.mstregistrations = mstregistrations;
	}

}
