package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mstschool generated by hbm2java
 */
@Entity
@Table(name = "mstschool", catalog = "dbschoolmanagementsystem")
public class Mstschool implements java.io.Serializable {

	private Integer intSchoolId;
	private String txtSchoolName;
	private Set<Mstschoolconnect> mstschoolconnects = new HashSet<Mstschoolconnect>(0);

	public Mstschool() {
	}

	public Mstschool(String txtSchoolName, Set<Mstschoolconnect> mstschoolconnects) {
		this.txtSchoolName = txtSchoolName;
		this.mstschoolconnects = mstschoolconnects;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intSchoolId", unique = true, nullable = false)
	public Integer getIntSchoolId() {
		return this.intSchoolId;
	}

	public void setIntSchoolId(Integer intSchoolId) {
		this.intSchoolId = intSchoolId;
	}

	@Column(name = "txtSchoolName", length = 50)
	public String getTxtSchoolName() {
		return this.txtSchoolName;
	}

	public void setTxtSchoolName(String txtSchoolName) {
		this.txtSchoolName = txtSchoolName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mstschool")
	public Set<Mstschoolconnect> getMstschoolconnects() {
		return this.mstschoolconnects;
	}

	public void setMstschoolconnects(Set<Mstschoolconnect> mstschoolconnects) {
		this.mstschoolconnects = mstschoolconnects;
	}

}
