package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Mststudent generated by hbm2java
 */
@Entity
@Table(name = "mststudent", catalog = "dbschoolmanagementsystem")
public class Mststudent implements java.io.Serializable {

	private Integer intStudentId;
	private String txtStudentName;

	public Mststudent() {
	}

	public Mststudent(String txtStudentName) {
		this.txtStudentName = txtStudentName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intStudentId", unique = true, nullable = false)
	public Integer getIntStudentId() {
		return this.intStudentId;
	}

	public void setIntStudentId(Integer intStudentId) {
		this.intStudentId = intStudentId;
	}

	@Column(name = "txtStudentName", length = 50)
	public String getTxtStudentName() {
		return this.txtStudentName;
	}

	public void setTxtStudentName(String txtStudentName) {
		this.txtStudentName = txtStudentName;
	}

}
