package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mstsubject generated by hbm2java
 */
@Entity
@Table(name = "mstsubject", catalog = "dbschoolmanagementsystem")
public class Mstsubject implements java.io.Serializable {

	private Integer intSubjectId;
	private Mststudclass mststudclass;
	private String txtSubjectName;
	private Set<Mststudenttimetable> mststudenttimetables = new HashSet<Mststudenttimetable>(0);
	private Set<Mstquestionandanswer> mstquestionandanswers = new HashSet<Mstquestionandanswer>(0);
	private Set<Mstregistration> mstregistrations = new HashSet<Mstregistration>(0);
	private Set<Mstteachertimetable> mstteachertimetables = new HashSet<Mstteachertimetable>(0);

	public Mstsubject() {
	}

	public Mstsubject(Mststudclass mststudclass, String txtSubjectName, Set<Mststudenttimetable> mststudenttimetables,
			Set<Mstquestionandanswer> mstquestionandanswers, Set<Mstregistration> mstregistrations,
			Set<Mstteachertimetable> mstteachertimetables) {
		this.mststudclass = mststudclass;
		this.txtSubjectName = txtSubjectName;
		this.mststudenttimetables = mststudenttimetables;
		this.mstquestionandanswers = mstquestionandanswers;
		this.mstregistrations = mstregistrations;
		this.mstteachertimetables = mstteachertimetables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intSubjectId", unique = true, nullable = false)
	public Integer getIntSubjectId() {
		return this.intSubjectId;
	}

	public void setIntSubjectId(Integer intSubjectId) {
		this.intSubjectId = intSubjectId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intClassId")
	public Mststudclass getMststudclass() {
		return this.mststudclass;
	}

	public void setMststudclass(Mststudclass mststudclass) {
		this.mststudclass = mststudclass;
	}

	@Column(name = "txtSubjectName", length = 50)
	public String getTxtSubjectName() {
		return this.txtSubjectName;
	}

	public void setTxtSubjectName(String txtSubjectName) {
		this.txtSubjectName = txtSubjectName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mstsubject")
	public Set<Mststudenttimetable> getMststudenttimetables() {
		return this.mststudenttimetables;
	}

	public void setMststudenttimetables(Set<Mststudenttimetable> mststudenttimetables) {
		this.mststudenttimetables = mststudenttimetables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mstsubject")
	public Set<Mstquestionandanswer> getMstquestionandanswers() {
		return this.mstquestionandanswers;
	}

	public void setMstquestionandanswers(Set<Mstquestionandanswer> mstquestionandanswers) {
		this.mstquestionandanswers = mstquestionandanswers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mstsubject")
	public Set<Mstregistration> getMstregistrations() {
		return this.mstregistrations;
	}

	public void setMstregistrations(Set<Mstregistration> mstregistrations) {
		this.mstregistrations = mstregistrations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mstsubject")
	public Set<Mstteachertimetable> getMstteachertimetables() {
		return this.mstteachertimetables;
	}

	public void setMstteachertimetables(Set<Mstteachertimetable> mstteachertimetables) {
		this.mstteachertimetables = mstteachertimetables;
	}

}
