package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mstterms generated by hbm2java
 */
@Entity
@Table(name = "mstterms", catalog = "dbschoolmanagementsystem")
public class Mstterms implements java.io.Serializable {

	private Integer intTermId;
	private String txtTermName;
	private Integer intStatus;
	private Set<Mstuploadstudmarksheet> mstuploadstudmarksheets = new HashSet<Mstuploadstudmarksheet>(0);
	private Set<Tblstudentperformance> tblstudentperformances = new HashSet<Tblstudentperformance>(0);

	public Mstterms() {
	}

	public Mstterms(String txtTermName, Integer intStatus, Set<Mstuploadstudmarksheet> mstuploadstudmarksheets,
			Set<Tblstudentperformance> tblstudentperformances) {
		this.txtTermName = txtTermName;
		this.intStatus = intStatus;
		this.mstuploadstudmarksheets = mstuploadstudmarksheets;
		this.tblstudentperformances = tblstudentperformances;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intTermId", unique = true, nullable = false)
	public Integer getIntTermId() {
		return this.intTermId;
	}

	public void setIntTermId(Integer intTermId) {
		this.intTermId = intTermId;
	}

	@Column(name = "txtTermName", length = 50)
	public String getTxtTermName() {
		return this.txtTermName;
	}

	public void setTxtTermName(String txtTermName) {
		this.txtTermName = txtTermName;
	}

	@Column(name = "intStatus")
	public Integer getIntStatus() {
		return this.intStatus;
	}

	public void setIntStatus(Integer intStatus) {
		this.intStatus = intStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mstterms")
	public Set<Mstuploadstudmarksheet> getMstuploadstudmarksheets() {
		return this.mstuploadstudmarksheets;
	}

	public void setMstuploadstudmarksheets(Set<Mstuploadstudmarksheet> mstuploadstudmarksheets) {
		this.mstuploadstudmarksheets = mstuploadstudmarksheets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mstterms")
	public Set<Tblstudentperformance> getTblstudentperformances() {
		return this.tblstudentperformances;
	}

	public void setTblstudentperformances(Set<Tblstudentperformance> tblstudentperformances) {
		this.tblstudentperformances = tblstudentperformances;
	}

}
