package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mstteachertimetable generated by hbm2java
 */
@Entity
@Table(name = "mstteachertimetable", catalog = "dbschoolmanagementsystem")
public class Mstteachertimetable implements java.io.Serializable {

	private Integer intTeacherTimeTableId;
	private Mstregistration mstregistration;
	private Mststudclass mststudclass;
	private Mststudclasssection mststudclasssection;
	private Mstsubject mstsubject;
	private Tbldaysofweek tbldaysofweek;
	private String txtClassTimings;
	private Integer intStatus;
	private byte[] blTeacherTimetable;
	private Set<Mstteachercheckin> mstteachercheckins = new HashSet<Mstteachercheckin>(0);

	public Mstteachertimetable() {
	}

	public Mstteachertimetable(Mstregistration mstregistration, Mststudclass mststudclass,
			Mststudclasssection mststudclasssection, Mstsubject mstsubject, Tbldaysofweek tbldaysofweek,
			String txtClassTimings, Integer intStatus, byte[] blTeacherTimetable,
			Set<Mstteachercheckin> mstteachercheckins) {
		this.mstregistration = mstregistration;
		this.mststudclass = mststudclass;
		this.mststudclasssection = mststudclasssection;
		this.mstsubject = mstsubject;
		this.tbldaysofweek = tbldaysofweek;
		this.txtClassTimings = txtClassTimings;
		this.intStatus = intStatus;
		this.blTeacherTimetable = blTeacherTimetable;
		this.mstteachercheckins = mstteachercheckins;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intTeacherTimeTableId", unique = true, nullable = false)
	public Integer getIntTeacherTimeTableId() {
		return this.intTeacherTimeTableId;
	}

	public void setIntTeacherTimeTableId(Integer intTeacherTimeTableId) {
		this.intTeacherTimeTableId = intTeacherTimeTableId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intRegistrationId")
	public Mstregistration getMstregistration() {
		return this.mstregistration;
	}

	public void setMstregistration(Mstregistration mstregistration) {
		this.mstregistration = mstregistration;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intClassId")
	public Mststudclass getMststudclass() {
		return this.mststudclass;
	}

	public void setMststudclass(Mststudclass mststudclass) {
		this.mststudclass = mststudclass;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intSectionId")
	public Mststudclasssection getMststudclasssection() {
		return this.mststudclasssection;
	}

	public void setMststudclasssection(Mststudclasssection mststudclasssection) {
		this.mststudclasssection = mststudclasssection;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intSubjectId")
	public Mstsubject getMstsubject() {
		return this.mstsubject;
	}

	public void setMstsubject(Mstsubject mstsubject) {
		this.mstsubject = mstsubject;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intDaysID")
	public Tbldaysofweek getTbldaysofweek() {
		return this.tbldaysofweek;
	}

	public void setTbldaysofweek(Tbldaysofweek tbldaysofweek) {
		this.tbldaysofweek = tbldaysofweek;
	}

	@Column(name = "txtClassTimings", length = 100)
	public String getTxtClassTimings() {
		return this.txtClassTimings;
	}

	public void setTxtClassTimings(String txtClassTimings) {
		this.txtClassTimings = txtClassTimings;
	}

	@Column(name = "intStatus")
	public Integer getIntStatus() {
		return this.intStatus;
	}

	public void setIntStatus(Integer intStatus) {
		this.intStatus = intStatus;
	}

	@Column(name = "blTeacherTimetable")
	public byte[] getBlTeacherTimetable() {
		return this.blTeacherTimetable;
	}

	public void setBlTeacherTimetable(byte[] blTeacherTimetable) {
		this.blTeacherTimetable = blTeacherTimetable;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mstteachertimetable")
	public Set<Mstteachercheckin> getMstteachercheckins() {
		return this.mstteachercheckins;
	}

	public void setMstteachercheckins(Set<Mstteachercheckin> mstteachercheckins) {
		this.mstteachercheckins = mstteachercheckins;
	}

}
