package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mstteacherinvite generated by hbm2java
 */
@Entity
@Table(name = "mstteacherinvite", catalog = "dbschoolmanagementsystem")
public class Mstteacherinvite implements java.io.Serializable {

	private Integer intteacherinviteId;
	private Mstregistration mstregistration;
	private Mststudclass mststudclass;
	private Mststudclasssection mststudclasssection;
	private String txtMessage;
	private Date dtInvitesDate;

	public Mstteacherinvite() {
	}

	public Mstteacherinvite(Mstregistration mstregistration, Mststudclass mststudclass,
			Mststudclasssection mststudclasssection, String txtMessage, Date dtInvitesDate) {
		this.mstregistration = mstregistration;
		this.mststudclass = mststudclass;
		this.mststudclasssection = mststudclasssection;
		this.txtMessage = txtMessage;
		this.dtInvitesDate = dtInvitesDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intteacherinviteId", unique = true, nullable = false)
	public Integer getIntteacherinviteId() {
		return this.intteacherinviteId;
	}

	public void setIntteacherinviteId(Integer intteacherinviteId) {
		this.intteacherinviteId = intteacherinviteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intRegistrationId")
	public Mstregistration getMstregistration() {
		return this.mstregistration;
	}

	public void setMstregistration(Mstregistration mstregistration) {
		this.mstregistration = mstregistration;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intClassId")
	public Mststudclass getMststudclass() {
		return this.mststudclass;
	}

	public void setMststudclass(Mststudclass mststudclass) {
		this.mststudclass = mststudclass;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intSectionId")
	public Mststudclasssection getMststudclasssection() {
		return this.mststudclasssection;
	}

	public void setMststudclasssection(Mststudclasssection mststudclasssection) {
		this.mststudclasssection = mststudclasssection;
	}

	@Column(name = "txtMessage", length = 200)
	public String getTxtMessage() {
		return this.txtMessage;
	}

	public void setTxtMessage(String txtMessage) {
		this.txtMessage = txtMessage;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dtInvitesDate", length = 10)
	public Date getDtInvitesDate() {
		return this.dtInvitesDate;
	}

	public void setDtInvitesDate(Date dtInvitesDate) {
		this.dtInvitesDate = dtInvitesDate;
	}

}
