package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mstuploadstudmarksheet generated by hbm2java
 */
@Entity
@Table(name = "mstuploadstudmarksheet", catalog = "dbschoolmanagementsystem")
public class Mstuploadstudmarksheet implements java.io.Serializable {

	private Integer intUploadStudMarksheetId;
	private Mstregistration mstregistration;
	private Mststudclass mststudclass;
	private Mststudclasssection mststudclasssection;
	private Mstterms mstterms;
	private byte[] blMarkSheet;
	private Date dtDate;
	private String txtfileName;
	private String txtcontentType;
	private Integer intTeacherId;

	public Mstuploadstudmarksheet() {
	}

	public Mstuploadstudmarksheet(Mstregistration mstregistration, Mststudclass mststudclass,
			Mststudclasssection mststudclasssection, Mstterms mstterms, byte[] blMarkSheet, Date dtDate,
			String txtfileName, String txtcontentType, Integer intTeacherId) {
		this.mstregistration = mstregistration;
		this.mststudclass = mststudclass;
		this.mststudclasssection = mststudclasssection;
		this.mstterms = mstterms;
		this.blMarkSheet = blMarkSheet;
		this.dtDate = dtDate;
		this.txtfileName = txtfileName;
		this.txtcontentType = txtcontentType;
		this.intTeacherId = intTeacherId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intUploadStudMarksheetId", unique = true, nullable = false)
	public Integer getIntUploadStudMarksheetId() {
		return this.intUploadStudMarksheetId;
	}

	public void setIntUploadStudMarksheetId(Integer intUploadStudMarksheetId) {
		this.intUploadStudMarksheetId = intUploadStudMarksheetId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intRegistrationId")
	public Mstregistration getMstregistration() {
		return this.mstregistration;
	}

	public void setMstregistration(Mstregistration mstregistration) {
		this.mstregistration = mstregistration;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intClassId")
	public Mststudclass getMststudclass() {
		return this.mststudclass;
	}

	public void setMststudclass(Mststudclass mststudclass) {
		this.mststudclass = mststudclass;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intSectionId")
	public Mststudclasssection getMststudclasssection() {
		return this.mststudclasssection;
	}

	public void setMststudclasssection(Mststudclasssection mststudclasssection) {
		this.mststudclasssection = mststudclasssection;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intTermId")
	public Mstterms getMstterms() {
		return this.mstterms;
	}

	public void setMstterms(Mstterms mstterms) {
		this.mstterms = mstterms;
	}

	@Column(name = "blMarkSheet")
	public byte[] getBlMarkSheet() {
		return this.blMarkSheet;
	}

	public void setBlMarkSheet(byte[] blMarkSheet) {
		this.blMarkSheet = blMarkSheet;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dtDate", length = 10)
	public Date getDtDate() {
		return this.dtDate;
	}

	public void setDtDate(Date dtDate) {
		this.dtDate = dtDate;
	}

	@Column(name = "txtfileName", length = 100)
	public String getTxtfileName() {
		return this.txtfileName;
	}

	public void setTxtfileName(String txtfileName) {
		this.txtfileName = txtfileName;
	}

	@Column(name = "txtcontentType", length = 200)
	public String getTxtcontentType() {
		return this.txtcontentType;
	}

	public void setTxtcontentType(String txtcontentType) {
		this.txtcontentType = txtcontentType;
	}

	@Column(name = "intTeacherId")
	public Integer getIntTeacherId() {
		return this.intTeacherId;
	}

	public void setIntTeacherId(Integer intTeacherId) {
		this.intTeacherId = intTeacherId;
	}

}
