package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tbladdresstype generated by hbm2java
 */
@Entity
@Table(name = "tbladdresstype", catalog = "dbschoolmanagementsystem")
public class Tbladdresstype implements java.io.Serializable {

	private Integer intAddressTypeId;
	private String txtAddressType;

	public Tbladdresstype() {
	}

	public Tbladdresstype(String txtAddressType) {
		this.txtAddressType = txtAddressType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intAddressTypeId", unique = true, nullable = false)
	public Integer getIntAddressTypeId() {
		return this.intAddressTypeId;
	}

	public void setIntAddressTypeId(Integer intAddressTypeId) {
		this.intAddressTypeId = intAddressTypeId;
	}

	@Column(name = "txtAddressType", length = 50)
	public String getTxtAddressType() {
		return this.txtAddressType;
	}

	public void setTxtAddressType(String txtAddressType) {
		this.txtAddressType = txtAddressType;
	}

}
