package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tblbankname generated by hbm2java
 */
@Entity
@Table(name = "tblbankname", catalog = "dbschoolmanagementsystem")
public class Tblbankname implements java.io.Serializable {

	private Integer intBankNameId;
	private String txtBankName;
	private Set<Mstbank> mstbanks = new HashSet<Mstbank>(0);
	public Tblbankname() {
	}

	public Tblbankname(String txtBankName, Set<Mstbank> mstbanks) {
		this.txtBankName = txtBankName;
		this.mstbanks = mstbanks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intBankNameId", unique = true, nullable = false)
	public Integer getIntBankNameId() {
		return this.intBankNameId;
	}

	public void setIntBankNameId(Integer intBankNameId) {
		this.intBankNameId = intBankNameId;
	}

	@Column(name = "txtBankName", length = 50)
	public String getTxtBankName() {
		return this.txtBankName;
	}

	public void setTxtBankName(String txtBankName) {
		this.txtBankName = txtBankName;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblbankname")
	public Set<Mstbank> mstbanks() {
		return this.mstbanks;
	}

	public void setMstbanks(Set<Mstbank> mstbanks) {
		this.mstbanks = mstbanks;
	}

}
