package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tbllocationlist generated by hbm2java
 */
@Entity
@Table(name = "tbllocationlist", catalog = "dbschoolmanagementsystem")
public class Tbllocationlist implements java.io.Serializable {

	private Integer intLocationId;
	private String txtLocationName;

	public Tbllocationlist() {
	}

	public Tbllocationlist(String txtLocationName) {
		this.txtLocationName = txtLocationName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intLocationId", unique = true, nullable = false)
	public Integer getIntLocationId() {
		return this.intLocationId;
	}

	public void setIntLocationId(Integer intLocationId) {
		this.intLocationId = intLocationId;
	}

	@Column(name = "txtLocationName", length = 50)
	public String getTxtLocationName() {
		return this.txtLocationName;
	}

	public void setTxtLocationName(String txtLocationName) {
		this.txtLocationName = txtLocationName;
	}

}
