package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tblrolename generated by hbm2java
 */
@Entity
@Table(name = "tblrolename", catalog = "dbschoolmanagementsystem")
public class Tblrolename implements java.io.Serializable {

	private Integer intRoleId;
	private String txtRoleName;
	private Set<Mstregistration> mstregistrations = new HashSet<Mstregistration>(0);
	private Set<Tblinvites> tblinviteses = new HashSet<Tblinvites>(0);
	private Set<Tbluserrole> tbluserroles = new HashSet<Tbluserrole>(0);

	public Tblrolename() {
	}

	public Tblrolename(String txtRoleName, Set<Mstregistration> mstregistrations, Set<Tblinvites> tblinviteses,
			Set<Tbluserrole> tbluserroles) {
		this.txtRoleName = txtRoleName;
		this.mstregistrations = mstregistrations;
		this.tblinviteses = tblinviteses;
		this.tbluserroles = tbluserroles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intRoleId", unique = true, nullable = false)
	public Integer getIntRoleId() {
		return this.intRoleId;
	}

	public void setIntRoleId(Integer intRoleId) {
		this.intRoleId = intRoleId;
	}

	@Column(name = "txtRoleName", length = 50)
	public String getTxtRoleName() {
		return this.txtRoleName;
	}

	public void setTxtRoleName(String txtRoleName) {
		this.txtRoleName = txtRoleName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblrolename")
	public Set<Mstregistration> getMstregistrations() {
		return this.mstregistrations;
	}

	public void setMstregistrations(Set<Mstregistration> mstregistrations) {
		this.mstregistrations = mstregistrations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblrolename")
	public Set<Tblinvites> getTblinviteses() {
		return this.tblinviteses;
	}

	public void setTblinviteses(Set<Tblinvites> tblinviteses) {
		this.tblinviteses = tblinviteses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblrolename")
	public Set<Tbluserrole> getTbluserroles() {
		return this.tbluserroles;
	}

	public void setTbluserroles(Set<Tbluserrole> tbluserroles) {
		this.tbluserroles = tbluserroles;
	}

}
