package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tblschoolandbranchdetail generated by hbm2java
 */
@Entity
@Table(name = "tblschoolandbranchdetail", catalog = "dbschoolmanagementsystem")
public class Tblschoolandbranchdetail implements java.io.Serializable {

	private Integer intSchoolId;
	private String txtSchoolAddress;
	private String txtResponsiblePerson;
	private String txtWebsite;
	private String txtSchoolName;
	private String txtEmail;
	private String txtSchoolContactNumber;

	public Tblschoolandbranchdetail() {
	}

	public Tblschoolandbranchdetail(String txtSchoolAddress, String txtResponsiblePerson, String txtWebsite,
			String txtSchoolName, String txtEmail, String txtSchoolContactNumber) {
		this.txtSchoolAddress = txtSchoolAddress;
		this.txtResponsiblePerson = txtResponsiblePerson;
		this.txtWebsite = txtWebsite;
		this.txtSchoolName = txtSchoolName;
		this.txtEmail = txtEmail;
		this.txtSchoolContactNumber = txtSchoolContactNumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intSchoolId", unique = true, nullable = false)
	public Integer getIntSchoolId() {
		return this.intSchoolId;
	}

	public void setIntSchoolId(Integer intSchoolId) {
		this.intSchoolId = intSchoolId;
	}

	@Column(name = "txtSchoolAddress", length = 200)
	public String getTxtSchoolAddress() {
		return this.txtSchoolAddress;
	}

	public void setTxtSchoolAddress(String txtSchoolAddress) {
		this.txtSchoolAddress = txtSchoolAddress;
	}

	@Column(name = "txtResponsiblePerson", length = 50)
	public String getTxtResponsiblePerson() {
		return this.txtResponsiblePerson;
	}

	public void setTxtResponsiblePerson(String txtResponsiblePerson) {
		this.txtResponsiblePerson = txtResponsiblePerson;
	}

	@Column(name = "txtWebsite", length = 200)
	public String getTxtWebsite() {
		return this.txtWebsite;
	}

	public void setTxtWebsite(String txtWebsite) {
		this.txtWebsite = txtWebsite;
	}

	@Column(name = "txtSchoolName", length = 200)
	public String getTxtSchoolName() {
		return this.txtSchoolName;
	}

	public void setTxtSchoolName(String txtSchoolName) {
		this.txtSchoolName = txtSchoolName;
	}

	@Column(name = "txtEmail", length = 50)
	public String getTxtEmail() {
		return this.txtEmail;
	}

	public void setTxtEmail(String txtEmail) {
		this.txtEmail = txtEmail;
	}

	@Column(name = "txtSchoolContactNumber", length = 50)
	public String getTxtSchoolContactNumber() {
		return this.txtSchoolContactNumber;
	}

	public void setTxtSchoolContactNumber(String txtSchoolContactNumber) {
		this.txtSchoolContactNumber = txtSchoolContactNumber;
	}

}
