package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tblstudentperformance generated by hbm2java
 */
@Entity
@Table(name = "tblstudentperformance", catalog = "dbschoolmanagementsystem")
public class Tblstudentperformance implements java.io.Serializable {

	private Integer intStudPerformanceId;
	private Mstregistration mstregistration;
	private Mststudclass mststudclass;
	private Mststudclasssection mststudclasssection;
	private Mstterms mstterms;

	public Tblstudentperformance() {
	}

	public Tblstudentperformance(Mstregistration mstregistration, Mststudclass mststudclass,
			Mststudclasssection mststudclasssection, Mstterms mstterms) {
		this.mstregistration = mstregistration;
		this.mststudclass = mststudclass;
		this.mststudclasssection = mststudclasssection;
		this.mstterms = mstterms;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intStudPerformanceId", unique = true, nullable = false)
	public Integer getIntStudPerformanceId() {
		return this.intStudPerformanceId;
	}

	public void setIntStudPerformanceId(Integer intStudPerformanceId) {
		this.intStudPerformanceId = intStudPerformanceId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intRegistrationId")
	public Mstregistration getMstregistration() {
		return this.mstregistration;
	}

	public void setMstregistration(Mstregistration mstregistration) {
		this.mstregistration = mstregistration;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intClassId")
	public Mststudclass getMststudclass() {
		return this.mststudclass;
	}

	public void setMststudclass(Mststudclass mststudclass) {
		this.mststudclass = mststudclass;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intSectionId")
	public Mststudclasssection getMststudclasssection() {
		return this.mststudclasssection;
	}

	public void setMststudclasssection(Mststudclasssection mststudclasssection) {
		this.mststudclasssection = mststudclasssection;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intTermId")
	public Mstterms getMstterms() {
		return this.mstterms;
	}

	public void setMstterms(Mstterms mstterms) {
		this.mstterms = mstterms;
	}

}
