package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tbluserrole generated by hbm2java
 */
@Entity
@Table(name = "tbluserrole", catalog = "dbschoolmanagementsystem")
public class Tbluserrole implements java.io.Serializable {

	private Integer intUserRoleId;
	private Mstregistration mstregistration;
	private Tblrolename tblrolename;
	private Integer intIsActive;
	private Date dtAssignedDate;

	public Tbluserrole() {
	}

	public Tbluserrole(Mstregistration mstregistration, Tblrolename tblrolename, Integer intIsActive,
			Date dtAssignedDate) {
		this.mstregistration = mstregistration;
		this.tblrolename = tblrolename;
		this.intIsActive = intIsActive;
		this.dtAssignedDate = dtAssignedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intUserRoleId", unique = true, nullable = false)
	public Integer getIntUserRoleId() {
		return this.intUserRoleId;
	}

	public void setIntUserRoleId(Integer intUserRoleId) {
		this.intUserRoleId = intUserRoleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intRegistrationId")
	public Mstregistration getMstregistration() {
		return this.mstregistration;
	}

	public void setMstregistration(Mstregistration mstregistration) {
		this.mstregistration = mstregistration;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intRoleId")
	public Tblrolename getTblrolename() {
		return this.tblrolename;
	}

	public void setTblrolename(Tblrolename tblrolename) {
		this.tblrolename = tblrolename;
	}

	@Column(name = "intIsActive")
	public Integer getIntIsActive() {
		return this.intIsActive;
	}

	public void setIntIsActive(Integer intIsActive) {
		this.intIsActive = intIsActive;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dtAssignedDate", length = 10)
	public Date getDtAssignedDate() {
		return this.dtAssignedDate;
	}

	public void setDtAssignedDate(Date dtAssignedDate) {
		this.dtAssignedDate = dtAssignedDate;
	}

}
