package com.seekdigital.entity;
// Generated Oct 17, 2016 10:09:49 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Trndocumentcategory generated by hbm2java
 */
@Entity
@Table(name = "trndocumentcategory", catalog = "dbschoolmanagementsystem")
public class Trndocumentcategory implements java.io.Serializable {

	private Integer intCategoryId;
	private String txtCategoryType;

	public Trndocumentcategory() {
	}

	public Trndocumentcategory(String txtCategoryType) {
		this.txtCategoryType = txtCategoryType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intCategoryId", unique = true, nullable = false)
	public Integer getIntCategoryId() {
		return this.intCategoryId;
	}

	public void setIntCategoryId(Integer intCategoryId) {
		this.intCategoryId = intCategoryId;
	}

	@Column(name = "txtCategoryType", length = 50)
	public String getTxtCategoryType() {
		return this.txtCategoryType;
	}

	public void setTxtCategoryType(String txtCategoryType) {
		this.txtCategoryType = txtCategoryType;
	}

}
